groups:
  - name: Fraud_Alerts
    rules:
      # Alert 1: Agar Fraud Recall 80% se gir jaye (Very Critical!)
      - alert: LowFraudRecall
        expr: model_fraud_recall < 0.80
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Model Recall dropped! Retraining triggered."

      # Alert 2: Agar Latency (speed) slow ho jaye
      - alert: HighApiLatency
        expr: http_request_duration_seconds > 0.5
        for: 2m
        labels:
          severity: warning
